import { Inter, Lora, Fira_Code } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

// Map Next fonts to the CSS variables you defined in globals.css
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const lora = Lora({
  variable: "--font-serif",
  subsets: ["latin"],
  display: "swap",
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Reborn Lombok Trans",
  description: "Generated by Reborn Lombok Trans",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="id"
      className={`${inter.variable} ${lora.variable} ${firaCode.variable}`}
    >
      {/* <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head> */}

      <body>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-RG3F0J2BDB"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-RG3F0J2BDB');
          `}
        </Script>

        {children}
        <Toaster />
      </body>
    </html>
  );
}
